### ISSUE TITLE
Sharing the session through all subdomains  

### ISSUE THREAD

**Issue by ondrek** [jaredhanson/passport#304]
Hello, I'd like to share a session through all subdomains.

Because Twitter doesn't allow `localhost` as a callback, I must use IP form `127.0.0.1` and all my subdomains are routed on `sub1.127.0.0.1`, `sub2.127.0.0.1` ..

<br>

Problem comes when I'm trying to set Express Session settings for all subdomains ..

    app.use(session({
      resave: false,
      saveUninitialized: true,
      cookie: { domain : ".127.0.0.1" }, // <-- this line and this dot before the IP
      secret: 'abc'
    }));

.. but it doesn't work and I get `Error: Failed to find request token in session` on url `http://127.0.0.1:3001/go/signup/callback?oauth_t...` in the Twitter callback.

<br>

It works well without `cookie` option in the session settings.

**Comment by gustavnikolaj** [comment]
This will not work, as subdomains exists as a DNS record that points to an IP and does not exist in the context of IPs. 

You should use something to define development domains instead of using 127.0.0.1. The simplest option is to just edit your operating systems host file, or make a DNS record on a real domain you own, that points to 127.0.0.1.

**Comment by ondrek** [comment]
.. well, 3 months later but still nice/usefull answer! thanks!
