### ISSUE TITLE
Standardized ensureAuthenticated

### ISSUE THREAD

**Issue by Schoonology** [jaredhanson/passport#385]
I couldn't find an existing discussion for this, but was surprised when there wasn't a standard, `passport`-provided method of _ensuring_ authentication in middleware. Instead, it appears as if users create their own `ensureAuthenticated` middleware like so:

```
function ensureAuthenticated(req, res, next) {
  if (!req.isAuthenticated()) {
    return res.redirect(...);
  }
  next();
}
```

With as common as this practice seems, I think there is a lot of value in `passport` providing this behaviour in a "standard" way, though users can implement their own versions as needed.

**Comment by Schoonology** [comment]
@jaredhanson - I'd be more than happy to submit a simple PR to this effect, if you're interested.

**Comment by jaredhanson** [comment]
https://github.com/jaredhanson/connect-ensure-login

Passport doesn't provide anything for this because this is mostly about session management and not authentication.  There are many ways to do this, and it is a highly-opinionated subject matter.  Part of Passport's appeal is its flexibility and ability to adapt to many opinions.
