### ISSUE TITLE
Certificate error for www.passportjs.org

### ISSUE THREAD

**Issue by retorquere** [jaredhanson/passport#547]
I'm getting a certificate error when I call up https://www.passportjs.org. https://passportjs.org is OK.

**Comment by S3curityPlu5** [comment]
I'm getting THIS SITE IS NOT SECURE for https://passportjs.org or https://www.passportjs.org in Microsoft Edge. 
Since this has not been fixed yet, is there anything planned to fix this problem, because we can use http, however when searching for passportjs in Bing, the first result is to the HTTPS://passportjs.org which will scare people away.

This site is not secure

This might mean that someone’s trying to fool you or steal any info you send to the server. You should close this site immediately.


Go to your Start page
Details 

The hostname in the website’s security certificate differs from the website you are trying to visit. 
Error Code: DLG_FLAGS_SEC_CERT_CN_INVALID
![passportjscerterror](https://cloud.githubusercontent.com/assets/3384853/24764461/68bc8b02-1ac2-11e7-8f01-694f6c69ab60.png)

**Comment by gka** [comment]
just get a [letsencrypt cert](https://letsencrypt.org/) for free! 

chrome is going to mark http sites as insecure soon enough 
https://www.cnet.com/news/chrome-warning-insecure-http-websites-expose-passwords-credit-card-numbers/

**Comment by jaredhanson** [comment]
The website is now available with TLS at https://www.passportjs.org.
