### ISSUE TITLE
Usage with Connect

### ISSUE THREAD

**Issue by mariolamacchia** [jaredhanson/passport#560]
Hello, thanks for this great library 👍 

[By reading the docs](http://passportjs.org/docs/authenticate#authenticate), it seems that passport works with Connect. However I get this error.
```
TypeError: res.redirect is not a function
    at complete (.../node_modules/passport/lib/middleware/authenticate.js:248:26)
```
Since Connect doesn't provide a `redirect` method, I could fix it just by adding a middleware before:
```
app.use(function(req, res, next) {
  res.redirect = function (url) {
    res.writeHead(302, { 'Location': url });
    res.end();
  }
  next();
});
```
I think it would be nice to either make sure that the APIs are compatible or to specify in the docs that you don't support using Passport with Connect.

**Comment by fruitl00p** [comment]
@mariolamacchia i just came accross this issue, but it appears you are mistaken as per [Express docs](https://expressjs.com/en/api.html#res.redirect) the response *does* have a redirect function... ? This might be something else entirely...

**Comment by mariolamacchia** [comment]
@fruitl00p Yes Express does have a redirect function, but I didn't even mention Express 😅 

Passport's docs say:

> Authenticating requests is as simple as calling passport.authenticate() and specifying which strategy to employ. authenticate()'s function signature **is standard Connect middleware**, which makes it convenient to use as route middleware in Express applications.

However [Connect](https://github.com/senchalabs/connect#readme) isn't supported since it passes to the callback a Node.js [`response` object](https://nodejs.org/api/http.html#http_class_http_serverresponse), which does not provide a `redirect` method.

**Comment by fruitl00p** [comment]
@mariolamacchia true, but it does state for usage in Express applications ;) It merely states it's function signature is the same, not that it actually supports Connect directly .. ?

**Comment by mariolamacchia** [comment]
Just saying, sure I misunderstood, but IMHO the docs aren't that clear for what concerns usage with *only* Express applications.

I mean, I've just tried to search for "express" in the [docs page](http://passportjs.org/docs):

> In a **Connect** or **Express**-based application, passport.initialize() middleware is required to initialize Passport. If your application uses persistent login sessions, passport.session() middleware must also be used.

> Authenticating requests is as simple as calling passport.authenticate() and specifying which strategy to employ. authenticate()'s function signature is standard **Connect** middleware, which makes it convenient to use as route middleware in **Express** applications.

Don't want to make a big deal about it but I think that **if** Passport is a middleware for only Express, it should be clearly stated in the first sentence:

> Passport is authentication middleware for ~Node~ Express.

**Comment by fruitl00p** [comment]
Agreed that the docs are a bit misleading... (I just haven't tested it with anything else than Express :))

**Comment by mariolamacchia** [comment]
Well the thing is that, except for that small thing, it does work with Connect! Plus, I've just noticed [this comment](https://github.com/jaredhanson/passport/blob/master/lib/middleware/authenticate.js#L311):

> NOTE: Do not use `res.redirect` from Express, because it can't decide what it wants.

I'll make a PR that replaces `res.redirect` with the custom implementation that is already there and we're good :)

**Comment by Panoplos** [comment]
I wholeheartedly agree with the ability to implement custom redirect, and there is a really good use case for it:

When I call `passport.authenticate('<strategy>'...)` from fetch, it will automatically attempt to redirect the browser to the strategy's service, which will result in a CORS error. I would like to have the freedom to implement a return of the service URL to the client so it can `window.location.replace(url)` to avoid this issue. Newer fetch versions have the ability to "manually" redirect, but it is only implemented in a few way edgy cases, and the RFC has not been yet even received input from Apple or MS.

The reasoning behind originating the authentication via a `fetch` is so that I can pass a header to associate the request with a session (and avoid cookies, which is not an ideal situation for a React Native client, for example.)

The only other option I have is to serve up the client with all the strategy-specific URLs, which kind of defeats the purpose of using this library.

**Comment by Panoplos** [comment]
Ugh...just looked at the code and realised this is not what it is allowing. I really recommend allowing for what I mentioned above, though.
