### ISSUE TITLE
React -> Express API -> 3rd Party OAUTH - CORS issues

### ISSUE THREAD

**Issue by mariocatch** [jaredhanson/passport#734]
I have a react app (site A), an express api (site B), and a 3rd party oauth service (site C).

In site A, I need the user to login to site C so they can utilize its resources. Since I don't want client id/secrets in my client (A), I setup site B to serve as a proxy between A and C.

```
A: localhost:3000
B: localhost:3001
C: example.com
```

I have a `"proxy": "http://localhost/3001"` setup in my `package.json`. So i can do things like `fetch('/api/foo')` in site A, and it'll hit site B successfully.

Here's where my confusion comes in. I have read the previous SO posts about CORS, but they only talk about site A to B, they dont factor in site C (a 3rd party api they dont own).

In site B, I am using `passport` and `passport-bnet` to handle the oauth. If I start up site B, and hit the oauth endpoint, it will successfully go out to site C and auth itself and bring back the token I need.

_BUT_ if I do something like this in site A:
```js
function Foo(() => {
  return <button onClick={handleOnClick}>Click Me</button>

  function handleOnClick() {
    // doesn't work
    fetch('/api/auth').then(...)
  }
});
```
Then I will receive a cors error.
> Access to fetch at 'https://us.battle.net/oauth/authorize?response_type=code&redirect_uri=http%3A%2F%2Flocalhost%3A3001%2Fauth%2Fbnet%2Fcallback&scope=wow.profile&client_id=.............' (redirected from 'http://localhost:3001/auth/bnet') from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

If I change my `<button>`'s `onClick` to an anchor tag, then it works:
```js
...
// works
return <a href="/api/auth">Click Me</a>
...
```

What am I missing here? Again, I've read the existing top cors answers on SO, but they only utilize two site (where you own both of them). I only own 2 of the 3 in this scenario.

_Note, site C does support http and https, and also supports localhost redirects (as proven by B -> C working correctly).

**Comment by mariocatch** [comment]
Fixed. Don't use `fetch` from react to api to oauth service. Use a link (anchor/location.href) instead and let the flow of the oauth process take over in the browser.

**Comment by artoodeeto** [comment]
@trustieee  bro can you show some code to your solution? I am having the same issue too. I used fetch then Im getting cors error. I wanted to use fetch because I want the `callbackURL` to respond a JSON data. Since I cant figure it out, I created a flow like this:


1. React FB login:
```js
export const FbBtn: FC<FbBtnProps> = () => <a href="http://localhost:8000/api/v1/auth/facebook">Login with Facebook</a>;
```

2. it will go to `auth/facebook` routes then will request for facebook user data. 

3. will trigger `callbackURL` after successful facebook authentication.

since I cant return a json data after fetch request. I had to do it like this.
4. respond with a cookie for the token and will redirect to frontend.

THE HACKY PART to get the user data!!!
5. On my frontend I created an intercept auth component that will request for user data: 
```js
export const InterceptAuth: FC<InterceptAuthProps> = () => {
  useEffect(() => {
    const tok = Cookies.get('ggpo_token');
    // ? should check token here????

    async function t() {
      const data = await fetch('http://localhost:8000/api/v1/auth/test', {
        headers: {
          Authorization: `Bearer ${tok}`
        }
      });
      console.log(data.json(), 'WHAATT??');
    }
    t();
  });

  return <div>...</div>;
};
```
I don't like the hacky part because its so redundant for getting the user data. can you share yours? thanks man.

**Comment by sethbro** [comment]
@trustieee I'm not clear what `InterceptAuth` does in your example. Wouldn't the `fetch` call there immediately fail due to the mentioned CORS errors?
