### ISSUE TITLE
The future of Passport.js

### ISSUE THREAD

**Issue by Glazy** [jaredhanson/passport#748]
Hey :wave:

Passport.js still remains the recommended way by many to implement authentication in Node.js applications. There are a lot of businesses that rely on this and there are also a lot of newcomers to Node being directed to this library by various videos and blog articles.

I noticed that there hasn't been a commit in 7 months and this has led me to wonder about the future of the project.

There are currently, as of writing, 308 open issues and 30 open pull requests. Quite a few of these issues and pull requests span back months or years and many don't have any responses.

I understand maintaining an open source library of this size and importance is tiresome work but I just wonder what the plans are for the future? How should we collectively go about triaging these issues and working our way through the open PRs?

Is there also work to be done on improving the documentation for the project? Last time I implemented Passport.js in a project I stumbled across this [alternate manual](https://github.com/jwalton/passport-api-docs), the existence of this probably indicates the official documentation could do with some work.

I also found similar sentiment in the [/r/node Reddit thread about the alternate documentation](https://www.reddit.com/r/node/comments/8hyp7k/passportjs_the_hidden_manual/).

Thanks,
Luke

**Comment by pke** [comment]
I just stumbled over this package on my search for authorisation middlewares for koajs.
The official sites /packages page is 404, this lead me to the issues tracker.

I'd like to see WebAuthn somehow integrated, there does not seem to be a strategy out there.

The idea behind the package is great and I hope we get a statement from the current maintainers.

**Comment by jaredhanson** [comment]
> There are currently, as of writing, 308 open issues and 30 open pull requests.
> How should we collectively go about triaging these issues and working our way through the open PRs?

Most of the 300+ open issues are actually not issues with this library, but support requests regarding problems with applications that have integrated passport for authentication.  Unfortunately, I do not have time to provide free support.  GitHub issues should be used to file demonstrable reports of bugs in the library itself which need fixing.

If anyone wants to volunteer, I would certainly appreciate help reading through the issues, and commenting or flagging them as support request, at which time I will close them.  A comment can be made to encourage people to file discussion-related questions at: https://github.com/passport/discuss

I will continue going through the open PRs and reviewing/merging them as I have time and urgency dictates.

> I'd like to see WebAuthn somehow integrated, there does not seem to be a strategy out there.

I have personally started on a WebAuthn strategy, but make no promises as to if or when it will be stable or usable.  Strategies are extensible, and can be community developed (as most strategies have been!), so feel free to contribute an implementation!

> The official sites /packages page is 404

You probably have JavaScript disabled in your browser, or the JavaScript had not yet loaded when you clicked the link.  This is a bug in the website itself, and does not impact the functionality or usablity of the library.

**Comment by jaredhanson** [comment]
Per my comment above, since this issue does not demonstrate a bug or functional issue with the library, I'm closing the issue.  Feel free to continue commenting or move discussion to https://github.com/passport/discuss

**Comment by pke** [comment]
Thanks Jared for responding so quickly. I agree GH issues should not be used for support questions (generally). I'm willing to flag them once you give me the required repo rights.

I headed over to https://github.com/passport/discuss and the most recent issues there are all unanswered/untagged for several months now. I wonder is there an active community for this package? Would pointing users to stackoverflow help?

The other day I found a working and pretty simple to wrap WebAuthn npm package over at https://github.com/wallix/webauthn 
Maybe we could use that as a starting point?

**Comment by ujwal-setlur** [comment]
Also, the website itself allows http access and does not auto-redirect to https. Second, the SSL cert does not match domain and flags a browser warning. This sends a wrong message, given that the passport library is pertaining security :)

**Comment by tadman** [comment]
It's 2021 and https://passportjs.org still doesn't resolve, plus https://www.passportjs.org has a busted cert, it's a *.herokuapp.com one.

GitHub Pages and Let's Encrypt solved this problem years ago.

Not a good look, but should be a relatively easy fix?

**Comment by pke** [comment]
@jaredhanson where is the sites code hosted? Maybe we could transform it to GH pages or deploy to vercel?

**Comment by johnredberg** [comment]
Posting here due to similarity with remarks noted in previous comments under this issue.

`www.passportjs.org` (note: `www` subdomain, without explicit `https` URI scheme) still serves plain, unencrypted HTTP traffic.

This may appear petty. But it's never a good look when you're reading the docs of a trendy framework (like in my case, [https://docs.nestjs.com/security/authentication](https://docs.nestjs.com/security/authentication)) click on a linked word ("strategies") and are greeted with "Not Secure."

@jaredhanson This should be an easy fix.

Cheers.

**Comment by jaredhanson** [comment]
> @jaredhanson This should be an easy fix.

What would be "fixed" by this?  The site is just serving up public documentation, there's no security sensitive credentials, cookies, or anything like that.   If someone wants to browse the site using plain HTTP, why shouldn't they be able to?

**Comment by tadman** [comment]
@jaredhanson Any HTTP site can be trivially injected with code by malicious networks, as but one of many reasons.

It's also an easy fix, there's no cost, no technical hurdles here. On GitHub Pages it's as easy as clicking a check-box.

**Comment by johnredberg** [comment]
@jaredhanson I honestly believe that there's nothing I can tell you on this subject that you don't already know. I can only report what my experience was and why I brought this issue up.

I clicked on a link that lead me to the documentation of an extremely popular authentication library and got a big fat "Not Secure" slapped next to the address bar in Chrome. That's a bad _look_. The phrase "Not Secure" for a library which is all about security _looks bad_. I'm not even arguing on a technical level here. Blame [Google](https://blog.google/products/chrome/milestone-chrome-security-marking-http-not-secure/), blame psychology, blame the uneducated public, blame VPN companies overselling the value of their services. The simple fact remains: _BAD LOOK._

So, here's what I did: I noticed the warning, decided to put in the time to bring this to your attention, found this issue, read through the comments, noticed that you apparently took previous comments to heart and figured you simply forgot one measly redirect. Then, I wrote my comment. Do or don't do with it as you please.

You're welcome.

**Comment by pke** [comment]
I agree this is easier to fix than this this discussion already lasts. There should be no http traffic anymore.

**Comment by tadman** [comment]
If nothing else, not having a secure site for the documentation for a *web site security tool*, is a really, really bad look.

"If they can't be bothered to click a checkbox and enable HTTPS, what other problems have they left unaddressed?"

This should be trivial to fix. If there are hurdles that prevent this from being an easy process, I'm sure we'd all like to help work through those, so just lay them out.

**Comment by jaredhanson** [comment]
> "If they can't be bothered to click a checkbox and enable HTTPS, what other problems have they left unaddressed?"

The website *is* available via HTTPS. It's _also_ available via HTTP.

I don't understand the rationale behind the idea that there should be no HTTP traffic anymore, especially for public information.  If I published the documentation in book form and put it on a shelf in a library, would that be problem because the "transport layer" of a physical book is not encrypted?  I'd love to hear a compelling reason why HTTP is problematic in this case and should be dropped.

I do understand that its a "bad look" when a browser puts a "Not Secure" badge next to the website's name.   But, the browser is warning the user about that in order to caution against submitting sensitive information to the website (which it doesn't ask for).   That warning has zero bearing on the Passport package and strategies themselves - which aren't even distributed via the website.  Enough people have filed issues about this, which indicates there is confusion about the correlation here (even though there is none).  Perhaps I should consider that reason enough to make a change.

But, at least at the present time, I still don't see the harm in serving via HTTP and don't consider this something that needs fixing.  As always, I remain open to change if there's a compelling reason.

**Comment by johnredberg** [comment]
Alright, I'll bite. 

1/ Let's say I'll give you your "HTTP until proven guilty" dogma, regardless what philosophical, psychological, technical, or anti-technical principles you've derived it from. As a fellow tech nerd, don't you value consistency in all its incarnations? Why does `http://passportjs.org` redirect to `https://www.passportjs.org` 
```
$ curl -I http://passportjs.org
HTTP/1.1 301 Moved Permanently
Location: https://www.passportjs.org/
Date: Thu, 06 Oct 2022 23:07:43 GMT
Content-Type: text/html; charset=UTF-8
Server: ghs
Content-Length: 224
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
```
but `http://www.passportjs.org` does not?
```
$ curl -I http://www.passportjs.org
HTTP/1.1 200 OK
Server: Cowboy
Connection: keep-alive
X-Powered-By: Express
Accept-Ranges: bytes
Date: Thu, 06 Oct 2022 23:08:45 GMT
Cache-Control: public, max-age=0
Last-Modified: Mon, 26 Sep 2022 21:40:51 GMT
Etag: W/"2080-4121873733"
Content-Type: text/html; charset=UTF-8
Content-Length: 8320
Via: 1.1 vegur
```
Shouldn't somebody who _opts in_ to HTTP not have their value system selectively disregarded? Is there an RFC I'm missing that recommends this behavior?

2/ Let's follow your book analogy. Last time I checked, libraries label their books, record them in a registry, and only then put them in a shelf. If I wanna read your book, I look it up in some sort of book name system, find its label which encodes some sort of address, which in turn finally points me to your book. Who's to say somebody didn't swap the labels? In the best case, I either find your original, or a completely different book (or none at all). In the worst case, I find a slightly altered version of your book, from which I blindly copy a few example code snippets which install a bunch of malware.

Sarcasm (almost) aside, SSL/TLS is a certificate-based system which verifies domain authenticity via some form of proof of ownership (why I am tell _you_ this?!). Once this trust is achieved, a secure channel is established _on top of that_. 

Isn't it in your best interest to assure visitors that they're reading your version of the "book", again, especially since your book is literally _all about authentication_?

**Comment by pke** [comment]
The fact that the browser messages are confusing users is in itself reason to change it, as you stated.

It also prevents 3rd parties injecting code during transfer. Which is an attack vector that was used in the past to distribute malware.
