### ISSUE TITLE
TypeError: req.logout is not a function

### ISSUE THREAD

**Issue by abzh423** [jaredhanson/passport#887]
I can log in and sign in getting the req.user and req.sessions successfully. But when I try to logout the user I get this error
```
TypeError: req.logout is not a function
    at C:\Users\abzh4\projects\bug-tracker\backend\src\routes\auth.ts:77:11
    at C:\Users\abzh4\projects\bug-tracker\backend\node_modules\.pnpm\connect-pg-simple@7.0.0\node_modules\connect-pg-simple\index.js:391:24
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
[ERROR] 15:02:39 TypeError: req.logout is not a function
```

P.S. I use typescript

* Operating System: Win 11
* Node version: 17.2
* passport version: 0.5.2

**Comment by jaredhanson** [comment]
Have you used `passport.authenticate()`  middleware prior to calling `req.logout()`?   That is necessary in order to add the `logout` function to `req`.  Typically you would have:

```
app.use(passport.authentication('session'));
```

in your app-level middleware stack.  Alternatively, if you want to no-op authentication, you can do `passport.authenticate('anonymous')`, using the [passport-anonymous](https://github.com/jaredhanson/passport-anonymous) strategy.

**Comment by abzh423** [comment]
Thanks, the order is indeed incredibly important. Seems to be a simple error, but I've spent 2 days finding out what is wrong.

**Comment by abzh423** [comment]
The solution: All you need is to put your routes after express-session and passport middleware.
