### ISSUE TITLE
Passport SAML is always chosen first by NestJS Passport, no matter the order

### ISSUE THREAD

**Issue by Fakerinc** [jaredhanson/passport#956]
When using NestJS and Passport to authenticate users, SAML will always be chosen as the first strategy. I'm providing passport several strategies as a fallback, but if SAML is somewhere in that array, it will always be the first to be checked.

### Expected behavior
I expect that Passport will try to use the provided stragies in the order they are passed.

### Actual behavior
If saml is somewhere defined in the array of strategies passed on to passport. The saml strategy will **always** be the first to be tried, regardless of the actual position in the passed array. It can be defined as the last strategy in the array and it will still be the first strategy to be tried.

### Steps to reproduce
1. Use NestJS and Passport for authentication
2. Create SAML Strategy
3. Provide passport basic and saml as a strategy
4. Start the authentication process
5. Notice that you will be redirected to SAML accessUrl

### Environment
Environment

Node.js version: 18.10.0
passport version: ^0.4.1

**Comment by jaredhanson** [comment]
Can you provide a code snippet illustrating how you are invoking Passport?   I suspect this issue should be filed with [Nestjs](https://github.com/nestjs/passport), but there's not enough information here to pinpoint exactly.

**Comment by Fakerinc** [comment]
I'm not 100% sure if this is what you are looking for. Please let me know if you need something else.

When booting the BE: 
```js
const server = express();

// serverconfig stuff

server.use(passport.initialize());
server.use((req, res, next) => {
  if (skipSession(req)) {
    next();
  } else {
    passport.session()(req, res, next);
  }
});

``` 

and here is the actual passport.auth() call wrapped in a custom function

```js
private async customAuth(context: ExecutionContext, request: Request, response: Response): Promise<boolean> {
    const user = await new Promise<User>(async (resolve, reject) => {
        const strats = await this.getStrats() // function returns passport-strategies as string[]. 

        return passport.authenticate(
          strats, {},
          (err, usr, info, status) => {
            try {
              request.authInfo = info;
              return resolve(this.handleRequest(err, usr, info, context, status));
            } catch (e: any) {
              reject(e);
            }
          })(request, response, (error) => (error ? reject(error) : resolve(null)));
      }
    );
    request.user = user;
    return !!user;
  }

```

**Comment by jaredhanson** [comment]
It would help to have some debugging around what the value of `strats` is.

Keep in mind that strategies like SAML will redirect any unauthenticated request to the SAML IDP.   Given that, its typically not common to use an array of redirect-based strategies, since the first one will redirect rather than fail and move onto the next one.   I suspect that's the behavior you are seeing, which is expected.

What other strategies are you attempting to supply in the array, and what use case are you trying to solve?

**Comment by Fakerinc** [comment]
Strats could look like this: const strats = ['basic', 'ldap', 'saml']; 
The string values, representing a strategy that was registered under the respective name. 

We are using the order of strategies defined in the strats array, to streamline the auth flow for each customer. We have the situation, that dev teams can configure the auth methods for each customer. Meaning, which auth strategies to use and the order in which they will be used/tried. So in the example provided above the basic login strategy would be tried first, then the auth against a ldap directory and in the end saml. Obviously this order doesn't make much sense. With most customers 'saml' is the first strategy to be tried as it provides the most comfort and functionality for the users. But let's just go with it. 

Of course you are right with the redirect behaviour of saml as a strategy itself, but this is not the behaviour I have an issue with. I have an issue with the fact, that although 'basic' and 'ldap' are defined before 'saml', these two strategies are ignored and the redirect to the saml idp is executed directly.  I would expect that the saml-strategy will be tried last, after 'basic' and 'ldap' failed.

 This worked pretty much flawlessly, up until the point where by coincidence 'saml' wasn't the first value in the strats array.

**Comment by jaredhanson** [comment]
What do you mean by the strategies being "ignored"?   What does the request to the endpoint in question look like?  If it lacks a username or password for basic (and presumably LDAP) authentication, those strategies will fail and move on to SAML.   They'd only be "not ignored" if credentials were supplied in the request.  Is that the case?

**Comment by Fakerinc** [comment]
It seems I am not expressing myself clearly. Sorry about that. I'll try again. 

We have integrated various passport-strategies and all of them work well. There is no issue on the level of requests or  similar. The problem is on a higher level. Please look at the following

1. Let's say my strats array looks like this: `const strats = ['ldap', 'basic']`. The user will be routed to our default loginPage and he will try to authenticate against the configured ldap and basic strategy in that order. I can see, when following the code, that the credentials of the user are beeing validated against the ldap interface first and then against the local db. This works wonderfully. 
  
2. Let's say my strats array looks like this: `const strats = ['saml', 'ldap', 'basic']`. The user will directly be routed to the login page of the saml idp and the rest of the strategies will be tried if saml fails. So again, the order of the strategies that are passed to passport, is being followed. This works wunderfully as well.
  
3. Let's say my strats array looks like this: `const strats = ['ldap', 'basic', 'saml']`. I would expect that the login strategies would be tried in the order provided above. Meaning, that the user would be routed to the default login page, and he would be able to put in his credentials and they would be validated wtih/against the 'ldap' and 'basic' strategy, and if these fail, the user would be redirected to the saml idp login page. **But this is not what happens.** 
The user is directly routed to the saml login page. This is what I mean with the other two strategies being ignored.

**Comment by jaredhanson** [comment]
I'm not sure how you are invoking passport and what options are using.  But, I'm assuming that the `failureRedirect` option is being used, based on the discussion.   That will trigger if _all_ strategies fail,  and redirect the user to the page requested.   So, if you have an endpoint like:

```
passport.authenticate(['ldap', 'basic'], { failureRedirect: '/login' });
```

Then if it receives a request without credentials, both strategies will fail and the request will be redirect to `/login` - which presumably prompts for a username and password.

Now, lets say you do this:

```
passport.authenticate(['ldap', 'basic', 'saml'], { failureRedirect: '/login' });
```

If this receives a request without credentials, the `ldap` and `basic` strategies will fail, but `saml` _will not fail_.  Instead, it will redirect the user to the SAML IDP.  In essence, the SAML strategy is overriding the `failureRedirect` option (since it needs to in order to function).  The other two strategies aren't "ignored", they are called and fail since they lack credentials.

Without a deeper understanding of the routes in your application, and what parameters they are invoked with, it's hard to make an exact diagnosis.   In general, I'd consider it an anti pattern to use `saml` in an array with `ldap` or `basic`.  It'd be cleaner to separate username/password authentication concerns from federated authentication.  But, again, without understanding the context of your application, it is hard to provide exact guidance.

**Comment by jaredhanson** [comment]
I see you closed the issue.  Could you provide a summary of how you resolved the issue so that others who encounter this in the future can troubleshoot?  Thanks.
